### ISSUE TITLE
radon_database docker container

### ISSUE THREAD

**Issue by nevrome** [MartinHinz/radon#1]
If we have a radon docker container we could also create a container that provides the radon database. Should depend on a postgres container and contain a reasonably up-to-date version of the original radon database.

**Comment by MartinHinz** [comment]
Why not? You are the Excecutive Officer of Virtualisation and Docker Evangelist, so go for it.

**Comment by MartinHinz** [comment]
After offline discussion... We postpone the decision, lets say, to the new year, and contemplate over the possibilities to divide handling of public and private data.
